/**
 * CONV-008 (real file): end-to-end PDF extraction through the compiled CLI.
 *
 * Jest's VM sandbox cannot run dynamic ESM imports (pdfjs-dist) without
 * --experimental-vm-modules. We therefore invoke the compiled binary as a subprocess —
 * the real Node.js process handles the ESM import natively.
 *
 * The fixture at test/fixtures/resumes/valid.pdf is generated by:
 *   node scripts/generate-pdf-fixture.js
 */

import { execFileSync } from 'child_process';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';

const PROJECT_ROOT = path.resolve(__dirname, '..', '..');
const VALID_PDF = path.resolve(__dirname, '../fixtures/resumes/valid.pdf');

describe('CONV-008 (real file): PDF extraction via compiled CLI', () => {
  let tmpIn: string;
  let tmpOut: string;
  let tmpPii: string;

  beforeAll(() => {
    tmpIn = fs.mkdtempSync(path.join(os.tmpdir(), 'rme-pdf-in-'));
    tmpOut = fs.mkdtempSync(path.join(os.tmpdir(), 'rme-pdf-out-'));
    tmpPii = fs.mkdtempSync(path.join(os.tmpdir(), 'rme-pdf-pii-'));
    fs.copyFileSync(VALID_PDF, path.join(tmpIn, 'valid.pdf'));
  });

  afterAll(() => {
    for (const d of [tmpIn, tmpOut, tmpPii]) fs.rmSync(d, { recursive: true, force: true });
  });

  it('parses valid.pdf and produces a profile containing name and skills', () => {
    const stdout = execFileSync(
      'node',
      ['dist/main.js', 'parse-resumes', tmpIn, '--out', tmpOut, '--pii-dir', tmpPii],
      { cwd: PROJECT_ROOT, encoding: 'utf8' },
    );
    expect(stdout).toContain('Parsed 1 resume(s)');

    const jsonFiles = fs.readdirSync(tmpOut).filter((f) => f.endsWith('.json'));
    expect(jsonFiles).toHaveLength(1);

    const profile = JSON.parse(fs.readFileSync(path.join(tmpOut, jsonFiles[0]), 'utf8'));
    // Skills must be extracted (the critical PDF path).
    expect(profile.skills.length).toBeGreaterThan(0);
    const canonicals = profile.skills.map((s: { canonical: string }) => s.canonical);
    expect(canonicals).toContain('TypeScript');
    expect(canonicals).toContain('Node.js');
    // No fatal conversion error — parser warnings (section detection) are acceptable.
    expect(profile.warnings.every((w: string) => !/could not be parsed/i.test(w))).toBe(true);
  });
});
